# Generated by Django 5.1.2 on 2024-10-22 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contato',
            new_name='Contact',
        ),
    ]
