from django import forms

from backend.models.paciente_model import Paciente


class PacienteForm(forms.ModelForm):
    title = "Informações Pessoais"
    class Meta:
        model = Paciente
        exclude = ("user",)
        fields = (
            "phone_number",
            "first_name",
            "last_name",
            "email",
            "cpf",
            "rg",
            "birth_date",
            "address",
            "estado_civil",
            "genero",
            "nome_responsavel",
            "telefone_responsavel",
            "grau_parentesco",
            "doencas_cronicas",
            "alergias",
            "medicamentos",
            "cirurgias",
            "historico_internacoes",
            "vacinas",
            "exames",
            "condicoes_cognitivas",
            "alteracoes_humor",
            "comportamento_social",
        )
        labels = {
            "nome_responsavel": "Nome do Responsável",
            "telefone_responsavel": "Telefone do Responsável",
            "grau_parentesco": "Grau de Parentesco",
            "phone_number": "Telefone",
            "first_name": "Nome",
            "last_name": "Sobrenome",
            "email": "Email",
            "cpf": "CPF",
            "rg": "RG",
            "birth_date": "Data de Nascimento",
            "address": "Endereço",
            "estado_civil": "Estado Civil",
            "genero": "Gênero",
            "doencas_cronicas": "Doenças Crônicas",
            "alergias": "Alergias",
            "medicamentos": "Medicamentos",
            "cirurgias": "Cirurgias",
            "historico_internacoes": "Histórico de Internações",
            "vacinas": "Vacinas",
            "exames": "Exames",
            "condicoes_cognitivas": "Condições Cognitivas",
            "alteracoes_humor": "Alterações no Humor",
            "comportamento_social": "Comportamento Social",
        }
        widget = {
            "phone_number": forms.TextInput(attrs={"class": "form-control", "type": "tel"}),
            "first_name": forms.TextInput(attrs={"class": "form-control"}),
            "last_name": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            "cpf": forms.TextInput(attrs={"class": "form-control"}),
            "rg": forms.TextInput(attrs={"class": "form-control"}),
            "birth_date": forms.DateInput(attrs={"class": "form-control", "type": "date"}),
            "address": forms.TextInput(attrs={"class": "form-control"}),
            "estado_civil": forms.Select(attrs={"class": "form-control"}),
            "genero": forms.Select(attrs={"class": "form-control"}),
            "nome_responsavel": forms.TextInput(attrs={"class": "form-control"}),
            "telefone_responsavel": forms.TextInput(attrs={"class": "form-control", "type": "tel"}),
            "grau_parentesco": forms.Select(attrs={"class": "form-control"}),
            "doencas_cronicas": forms.TextInput(attrs={"class": "form-control"}),
            "alergias": forms.TextInput(attrs={"class": "form-control"}),
            "medicamentos": forms.TextInput(attrs={"class": "form-control"}),
            "cirurgias": forms.TextInput(attrs={"class": "form-control"}),
            "historico_internacoes": forms.TextInput(attrs={"class": "form-control"}),
            "vacinas": forms.TextInput(attrs={"class": "form-control"}),
            "exames": forms.TextInput(attrs={"class": "form-control"}),
            "condicoes_cognitivas": forms.TextInput(attrs={"class": "form-control"}),
            "alteracoes_humor": forms.TextInput(attrs={"class": "form-control"}),
            "comportamento_social": forms.TextInput(attrs={"class": "form-control"}),            
        }
